github:
  is_project_page: false
theme: jekyll-theme-hacker
title: Nina Klobas
logo: slika.jpg
description: Durham University, Durham, United Kingdom;  nina.klobas@durham.ac.uk

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
