github:
  is_project_page: false
theme: jekyll-theme-hacker
title: Nina Klobas
logo: slika.jpg
description: Nina Klobas

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
  
  
google_analytics: G-9TG55YR35G

