github:
  is_project_page: false
theme: jekyll-theme-hacker
title: Nina Klobas
logo: slika.jpg

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
  
  
ga_tracking: G-9TG55YR35G
ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true by default)

